- .markdownlint.json
Update markdownlint config to allow inline HTML.
> Allow inline HTML

- source/tools/kubernetes/dask-helm-chart.md
Fixes: https://github.com/rapidsai/deployment/issues/31
> Updated service ports to 8888 (jupyter) and 8787 (dask scheduler)

- ci/docs/build.sh
This creates the required build script for the deployment of the docs generated in this repository.
> Create docs build.sh

- source/tools/kubernetes/dask-helm-chart.md
closes #26, instead of pasting an inline block, I think it's better to point to the official doc page for how to do this.
> Add instructions to compute password hash

- source/cloud/gcp/index.md
- source/cloud/gcp/single-node.md
> DOCS: Add instructions to install RAPIDS on GCP VM Single Instance

- source/tools/kubernetes/dask-kubernetes.md
- source/tools/kubernetes/dask-kubernetes/gpu-worker-spec.yaml
This PR adds a minimalistic style guide to setup dask-kubernetes in BYOC situations.
closes #5
> Add Dask-Kubernetes Rapids Setup Guide

- README.md
I just released `v22.10.00` and all went well. Documenting the steps I followed.
> Add release instructions to the README

- source/cloud/gcp/compute-engine.md
- source/cloud/gcp/index.md
- source/cloud/gcp/vertex-ai.md
Also fixes other typos I made in the GCP guides.
> Add links to Google VM GPU sizes and availabilities

- source/cloud/gcp/vertex-ai.md
> Update Vertex AI old RAPIDS note

- source/guides/azure/infiniband.md
- source/guides/index.md
- source/index.md
Related to #68 
SNMG updates from [Jacob's gist](https://gist.github.com/jacobtomlinson/6242a3547d13d4e7a00cc768b8b475c8)
> IB on Azure guide

- source/_includes/install-rapids-with-docker.md
- source/cloud/azure/azure-vm.md
Let me know if I should hold off on updating the anticipated image tag for nvcr
> Add SSH instructions to connect to AzureVM

- source/_includes/menus/gcp.md
- source/cloud/gcp/gke.md
- source/cloud/gcp/index.md
> Add GKE instructions

- source/cloud/gcp/vertex-ai.md
Tested the Vertex AI instructions for 22.12. I added the image name explicitly and did some minor style refactoring of the page to make it similar to other pages. Also added a quick cudf example to the bottom to verify things work.
> Update Vertex AI for 22.12

- source/cloud/aws/eks.md
Update AWS EKS instructions to be consistent with #82 #83
> Update EKS instructions

- source/_includes/menus/azure.md
- source/cloud/azure/aks.md
- source/cloud/azure/index.md
> Add Azure Kubernetes Service instructions

- source/tools/kubernetes/dask-helm-chart/rapids-config.yaml
This PR bumps image version for rapids helm chart instructions to 22.12.
> Bump Rapids Image Version for Rapids-helm-chart

- source/cloud/gcp/dataproc.md
Fixes  https://github.com/rapidsai/deployment/issues/94
> Update dataproc instructions

- source/cloud/gcp/dataproc.md
Fixes https://github.com/rapidsai/deployment/issues/101
> Remove warning on dataproc docs

- source/platforms/databricks.md
Fixes: https://github.com/rapidsai/deployment/issues/92
> Document deploying rapids on databricks

- README.md
Superficial change to the README.
> Tag diagram in README was pretty huge, made smaller

- source/guides/scheduler-gpu-requirements.md
> Add example failure modes for scheduler without GPU

- source/tools/rapids-docker.md
Updating this page to be consistent with the instructions on the Local install page.
Ideally I would like this page to have instructions on building your own images at some point, but this is fine for now.
> Improve container docs consistency

- source/tools/kubernetes/dask-operator.md
Updates dask-operator page with latest package name and fixes the client code
> [DOC]: Updates dask-operator page with latest package name and fixes the client code

- .readthedocs.yaml
Add config so that RTD installs the conda environment.
> Add Read The Docs config

- source/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook.ipynb
> Add tags to autoscaling kubernetes notebook

- source/cloud/gcp/gke.md
closes #206
Everything else looks good.
> Fix clustername in command

- source/examples/xgboost-randomforest-gpu-hpo-dask/notebook.ipynb
Follow on to #174 
Closes #202 
- Fix broken import
- Fix missing data URL
- Clean up formatting a little
> HPO notebook fixes

- source/platforms/index.md
- source/platforms/kserve.md
Closes https://github.com/rapidsai/cloud-ml-examples/issues/240
For now, document examples with tree models. We should eventually add examples with other RAPIDS models too.
> Add a new page for KServe

- source/hpc.md
> Add content warning to HPC page

- source/cloud/index.md
- source/local.md
Aligns pip instructions with current docs.
See also: https://github.com/rapidsai/docs/pull/377
> Revise pip instructions.

- source/guides/index.md
- source/guides/l4-gcp.md
xref https://github.com/rapidsai/deployment/issues/209
A lot of sections were taken from the existing GCP VM configuration section.
> DOC: Add guide configuring GCP VM with L4 GPU

- source/tools/kubernetes/dask-helm-chart.md
As a part of #236 : Fix types in Dask Helm Chart doc https://docs.rapids.ai/deployment/nightly/tools/kubernetes/dask-helm-chart/
> Fix typos in Dask Helm Chart Docs

- source/conf.py
Just updates for v23.06 release
> Updates for v23.06 release

- source/local.md
> Fix WSL2 link

- source/guides/l4-gcp.md
Closes #267
- Expose port 22 to enable SSH
- Increase boot drive size
- Remove installing NVIDIA apt sources, they seem to already exist in recent images
> Update L4 guide

- source/examples/xgboost-rf-gpu-cpu-benchmark/notebook.ipynb
Fixes https://github.com/rapidsai/deployment/issues/278
> Update tco benchmaking notebook with VM instance types

- .github/workflows/build-and-deploy.yml
We recently changed some paths in our documentation bucket.
This PR updates the `rapidsai/deployment` repository accordingly.
Additionally, it updates the composite actions used by the repository.
> Update docs upload path

- source/tools/dask-cuda.md
> Update dask-cuda tutorial

- source/conf.py
- source/platforms/kubernetes.md
> Update Kubernetes docs to use notebooks container

- source/conf.py
Bump versions for the `23.10` release
> Update to 23.10

- source/examples/rapids-ec2-mnmg/notebook.ipynb
> Update API for haversine and predictions output in notebook.ipynb

- source/cloud/aws/index.md
> Update AWS instance types

- source/cloud/azure/index.md
> Add H100 Azure VM types

- source/platforms/colab.md
~~- [ ] add pip nightly instructions~~ Next PR
> update colab instructions to deprecate conda, show cudf preinstalled on colab

- source/conf.py
Just roll over the versions for the `24.06` release.
> Updates for 24.06 release

- source/cloud/azure/azure-vm.md
I had trouble finding specific buttons because some intermediary steps were omitted 
Added more detailed steps
> added more detailed instructions to create security group

- source/_includes/check-gpu-pod-works.md
- source/cloud/azure/aks.md
> deleted $ for multiline commands

- source/conf.py
- source/platforms/databricks.md
- Made it clear you need to click "Add" for the user script
- Updated pip commands
- Added more templating for pip commands
> Tweak Databricks install instructions

- source/cloud/gcp/vertex-ai.md
Updated to CUDA 12 and uses templating from #482
> Update Vertex AI pip install command

- source/conf.py
Looks like this bump got missed during the last release process. Bumping it now.
> Update stable to 24.12 and nightly to 25.02

- source/platforms/snowflake.md
- Closes https://github.com/rapidsai/deployment/issues/535
I tested this and the workflow works, I found in the process some typos and a mistake in the spec `yaml` that now is raised in snowflake side that got fixed.
> Update snowflake docs to login via snow cli - mfa caching compatible

- source/cloud/azure/azure-vm.md
It took me a minute to figure out what the default username was for this VM type. Setting it explicitly here.
> Explicitly mention azureuser as the username for SSHing to an Azure VM

- README.md
- source/conf.py
Update rapids version to 25.04
> Update rapids version to 25.04

- .pre-commit-config.yaml
- source/examples/rapids-sagemaker-hpo/HPODatasets.py
- source/examples/xgboost-dask-databricks/notebook.ipynb
- source/examples/xgboost-randomforest-gpu-hpo-dask/notebook.ipynb
Run `pre-commit autoupdate` and then fix linting issues.
> Update pre-commit hooks

- source/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook.ipynb
Closes https://github.com/rapidsai/deployment/issues/467
> Add missing dependency in xgboost-gpu-hpo-job-parallel-k8s

- source/examples/cuml-snowflake-nb/notebook.ipynb
- source/examples/rapids-1brc-single-node/notebook.ipynb
- source/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook.ipynb
- source/examples/rapids-azureml-hpo/notebook.ipynb
- source/examples/rapids-coiled-cudf/notebook.ipynb
- source/examples/rapids-ec2-mnmg/notebook.ipynb
- source/examples/rapids-morpheus-pipeline/notebook.ipynb
- source/examples/rapids-optuna-hpo/notebook.ipynb
- source/examples/rapids-sagemaker-higgs/notebook.ipynb
- source/examples/rapids-sagemaker-hpo/notebook.ipynb
- source/examples/rapids-snowflake-cudf/notebook.ipynb
- source/examples/time-series-forecasting-with-hpo/notebook.ipynb
- source/examples/xgboost-azure-mnmg-daskcloudprovider/notebook.ipynb
- source/examples/xgboost-dask-databricks/notebook.ipynb
- source/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook.ipynb
- source/examples/xgboost-gpu-hpo-mnmg-parallel-k8s/notebook.ipynb
- source/examples/xgboost-randomforest-gpu-hpo-dask/notebook.ipynb
- source/examples/xgboost-rf-gpu-cpu-benchmark/notebook.ipynb
Closes https://github.com/rapidsai/deployment/issues/576 
Closes  https://github.com/rapidsai/deployment/issues/586
I set dates in the format `_Month, YYYY_`, and I took the dates from when they were added to https://github.com/rapidsai/deployment/blame/main/source/examples/index.md
> Add dates to workflow examples
