rapidsai/deployment

.github/workflows/build-and-deploy.yml

Add workflow to build docs and optionally deploy it.
All PRs will have the docs built as part of general testing that things are working ok.
If on `main` in the upstream `rapidsai/deployment` repo built HTML files are also committed to [the docs repo](https://github.com/rapidsai/docs/tree/gh-pages/deployment/) for publishing. Regular commits to `main` will be put at the `/deployment/nightly` path and tagged commits to the `/deployment/stable` path.
Closes #46

Add build and deploy workflow

---

source/platforms/kubeflow.md

I'm trying to simplify the Dask Operator install command, switching to helm in most places.
Works around https://github.com/dask/dask-kubernetes/issues/508 which @hcho3 ran into recently.

Change Dask Operator install command to helm one liner

---

source/cloud/aws/single-node.md

As mentioned in this [comment](https://github.com/rapidsai/deployment/issues/14#issuecomment-1247275106) in https://github.com/rapidsai/deployment/issues/14, setting up `Docker-CE/ Nvidia Container Tookit `on `Amazon Linux 2 AMI `isn't as straightforward.
This PR updates the `single-node.md` file with the following changes:
- Recommends `NVIDIA GPU-Optimized Deep Learning AMI` as the optimal choice,  with pre-installed Ubuntu OS, GPU driver, Docker and NVIDIA container toolkit
- Update  instructions to build the latest RAPIDS docker image `v22.10`

Update docs for AWS Single Instance (SNMG)

---

source/cloud/ibm/index.md

It has come to my attention in #49 that bare metal instances on IBM have a monthly billing interval rather than the standard hourly.
This means spinning one up will instantly hit you with a large charge. I want to be sure we clearly document that to avoid users unknowingly getting large charges.

Add warning about bare metal instance billing

---

.gitignore
source/conf.py
source/index.md
source/mig.md

Recently the interest for deploying Dask with Multi-Instance GPUs (MIG) has grown, therefore we add a getting started page, also communicating some of the limitations of MIG in an HPC context.

Add page on Multi-Instance GPU (MIG)

---

.markdownlint.json
.markdownlintignore
.pre-commit-config.yaml
source/_includes/install-rapids-with-docker.md
source/_includes/menus/aws.md
source/_includes/menus/azure.md
source/_includes/menus/gcp.md
source/_includes/menus/ibm.md
source/_includes/test-rapids-docker-vm.md
source/cloud/aws/ec2.md
source/cloud/aws/index.md
source/cloud/azure/azure-vm.md
source/cloud/azure/index.md
source/cloud/gcp/compute-engine.md
source/cloud/gcp/index.md
source/cloud/ibm/index.md
source/cloud/ibm/virtual-server.md
source/cloud/index.md

We now have Single Node examples for AWS, Azure, GCP and IBM Cloud but they were all slightly different.
This PR is a refactor inspired from the best of each page to make them all consistent with each other.
I've also used some includes so that duplicated sections like pulling the Docker image and testing the RAPIDS install is only written once. 
I also tweaked the menus a bit.

Align single node examples

---

source/_includes/install-rapids-with-docker.md
source/cloud/gcp/compute-engine.md

- Update container image to `22.12` (used DockerHub as NGC images are not yet published)
- Added some clean up instructions.

Update GCP Instance instructions for 22.12

---

source/cloud/aws/ecs.md

The ECS docs here are copied from rapids.ai/cloud and most likely do not work, we have a ticket open to track rewriting it (#79) but it didn't make it into 22.12.
I'm keen to get rapids.ai/cloud redirecting here because the majority of the documentation has been updated and the deployment docs are a much more useful resource than rapids.ai/cloud. So I want to clearly signal that this page is still legacy with a warning and go ahead with the redirect.

Add legacy warning to ECS docs

---

source/_includes/menus/gcp.md
source/cloud/gcp/dataproc.md
source/cloud/gcp/index.md

Given that https://github.com/rapidsai/cloud-ml-examples/issues/85 hasn't landed in 22.12 I propose migrating the instructions from rapids.ai/cloud directly here with a warning so that we can go ahead and redirect rapids.ai/cloud here. This leaves us in no worse position than we are already in and it would be better for users to have them on the new docs given that the majority of it has been updated.

Add legacy Dataproc page

---

source/platforms/databricks.md
source/platforms/index.md

The Databricks page is still a stub which may be confusing for users. Created #92 to track populating the page and removing the stub for now.

Delete Databricks stub for now

---

source/tools/index.md
source/tools/kubernetes/dask-gateway.md

#8 didn't make it into 22.12 so proposing we remove the stub pages for now. They can be recreated when #8 lands.

Delete Gateway stub for now

---

source/_includes/menus/azure.md
source/cloud/azure/azureml.md
source/cloud/azure/index.md

#15 didn't land in 22.12 so adding the legacy page with a warning for now.

Add legacy AzureML docs

---

README.md
conda/environments/deployment_docs.yml

Building the docs no longer requires a GPU or cudf, this simplifies the setup as you no longer need a GPU or a bleeding edge build of cudf.
I also added pre-commit to the environment file. Seems like a good way to get the tool without needing instructions for different platforms.

Simplify development setup instructions

---

.gitignore
conda/environments/deployment_docs.yml
extensions/rapids_notebook_files.py
source/_templates/notebooks-extra-files-nav.html
source/conf.py
source/examples/index.md
source/examples/rapids-sagemaker-higgs/Dockerfile
source/examples/rapids-sagemaker-higgs/notebook.ipynb
source/examples/rapids-sagemaker-higgs/rapids-higgs.py
source/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook.ipynb
source/index.md

Closes #105. 
To start this PR I copied a couple of notebooks from Cloud ML Examples so I had some pages to work with. I think a good structure for storing notebooks in this repo is to create a new directory for each notebook in the `examples` section containing the notebook and all the supporting files.
```
source/examples
├── index.md
├── rapids-sagemaker-higgs
│   ├── Dockerfile
│   ├── notebook.ipynb
│   └── rapids-higgs.py
└── xgboost-gpu-hpo-job-parallel-k8s
└── notebook.ipynb
```
I've also updated the site index to link to this new examples section instead of the Cloud ML Examples repo and I've manually created an index page with a card grid for the examples in the same way we have done with other index pages. In the future, this index should be replaced with an autogenerated one …

Add some example notebooks and a notebook related files sidebar item

---

.pre-commit-config.yaml
pyproject.toml
source/conf.py
source/examples/rapids-sagemaker-higgs/rapids-higgs.py

Folks seem to be excited about [ruff](https://github.com/charliermarsh/ruff) as a fast replacement for `flake8`/`isort`/`pyupgrade`/etc. 
Using it in the deployment docs for linting the example scripts and Sphinx extensions felt like a low-effort/low-risk place to try it out.
I've added it to the `pre-commit` config so it will get run on commit and in CI. You can optionally install it yourself with `pip install ruff` and run it on files with `ruff path/to/file.py`.

Add ruff to the repo linters

---

extensions/rapids_related_examples.py
source/_includes/menus/aws.md
source/_includes/menus/azure.md
source/_includes/menus/gcp.md
source/_includes/menus/ibm.md
source/_static/css/custom.css
source/_static/js/notebook-gallery.js
source/_templates/notebooks-tag-filter.html
source/conf.py
source/examples/index.md
source/examples/rapids-sagemaker-higgs/notebook.ipynb
source/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook.ipynb
source/guides/index.md
source/index.md
source/platforms/index.md

Closes #106. With this PR the example notebooks are shown in a gallery and can be filtered by their tags.
This change is made up of a few pieces:
- A custom toctree directive which generates a card table using the same notebook card generator from #111 
- _NB this approach would be useful for closing #115 in a follow up PR_
- A custom sidebar template for the examples index page with filtering checkboxes generated from the tag tree
- Some client-side JavaScript that hides/shows notebook cards based on the filter checkboxes
- Some custom CSS which styles the filter sidebar and colours the tags
- I changed the tag style from `bdg-primary` to `bdg` throughout the site so the custom tag styling would work correctly on all pages

Add notebook gallery with tag filter

---

extensions/rapids_related_examples.py
source/_static/css/custom.css
source/_static/js/notebook-gallery.js
source/_templates/notebooks-tags.html
source/conf.py

Add notebook tags visibly on the notebook page. Closes #109. 
I went with a sidebar for displaying the tags as it was much easier to implement than plugging into the MyST-NB parser.
I also updated the examples gallery so that when you check the filter boxes it updates the URL with a query parameter. Then on page load it looks for any tags in the URL and updates the checkboxes initial state. This allows us to link to the examples gallery with filters already checked.
I then made the tags on the notebook pages links to the gallery with that tag already filtered.
https://github.com/rapidsai/deployment/blob/ea9dac887a0c164e4fb2450d3f016f2ce3eb84ac/source/_templates/notebooks-tags.html#L6-L8

Add notebook tag sidebar

---

extensions/rapids_related_examples.py

Fixes #120.
It seems that putting `toctree` nodes inside a `nodes.section` node causes this duplicating behaviour. No idea why. Putting both the `section` and the hidden `toctree` inside a top-level `nodes.container` node resolves it 🤷‍♂️.
```
section
├── other stuff
└── toctree
container
├── section
│   └── other stuff
└── toctree
```

Fix duplicated entries in examples sidebar section nav

---

extensions/rapids_card_toctree.py
extensions/rapids_grid_toctree.py
source/conf.py
source/guides/index.md
source/index.md
source/platforms/index.md
source/tools/index.md

On many index pages we display a grid of cards for navigation because they look nicer than the default toctree bullet list
However we still have to include the hidden toctree element on each page to ensure the Sphinx navigation is generated correctly.
For example in `source/guides/index.md` we have the card grid for navigation.
https://github.com/rapidsai/deployment/blob/18280348ab1648855ff7e076b4d76f419ae9734e/source/guides/index.md?plain=1#L7-L31
And the hidden toctree with the same entries.
https://github.com/rapidsai/deployment/blob/18280348ab1648855ff7e076b4d76f419ae9734e/source/guides/index.md?plain=1#L33-L40
This PR adds a custom directive called `gridtoctree` which extends the [`grid` from sphinx-design](https://sphinx-design.readthedocs.io/en/latest/grids.html#grids) to …

Add Grid Toctree custom directive

---

.pre-commit-config.yaml
source/_includes/test-rapids-docker-vm.md
source/cloud/aws/ecs.md
source/cloud/azure/azure-vm-multi.md
source/cloud/gcp/vertex-ai.md
source/examples/rapids-sagemaker-higgs/notebook.ipynb
source/examples/rapids-sagemaker-higgs/rapids-higgs.py
source/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook.ipynb
source/platforms/kubeflow.md
source/tools/kubernetes/dask-kubernetes.md
source/tools/kubernetes/dask-operator.md

When migrating notebooks across I've noticed that some of them have unusual code styles. As usual, when code style comes up I just like to run black on things and stop worrying about it.
This PR adds two `pre-commit` hooks, one with `black[jupyter]` which runs on all `.py` and `.ipynb` files and one called `blacken-docs` which runs on any ` ```python ... ``` ` code fence in a markdown file.

Add black to pre-commit

---

source/tools/kubernetes/dask-operator.md

`limit` => `limits` 
With this typo the cluster still gets created, but without GPUs. This took far too long to debug, we should probably open an issue on `dask-kubernetes` to do some better validation on the input config.
I also took the opportunity to bump the RAPIDS image to `22.12` as that's what I'm using.

Fix typo in dask-operator instructions

---

source/platforms/kubernetes.md

Deploying an interactive single-user notebook on Kubernetes can provide a great place to launch further resources. For example, you could install `dask-kubernetes` and use the Dask Operator to create multi-node Dask clusters from your notebooks.
I've added an extra optional section to the Kubernetes Interactive Notebook deployment instructions which shows the extra steps you need to be able to use `dask-kubernetes` from within the notebook.
I used this for a demo at PyData DC last night and it was really neat launching a GKE cluster, running a RAPIDS Notebook pod and then bursting out from that onto an MNMG RAPIDS cluster.

Add optional extended notebook config to enable dask-kubernetes

---

extensions/rapids_notebook_files.py
source/_static/css/custom.css
source/_templates/notebooks-extra-files-nav.html

Minor tweak to related files to ensure directories are sorted at the top and have a trailing slash to show they are a directory. Also changed to a monospace font.
Also added a couple of base tag styles for `workflow` and `dataset`.

Style changes to related files and tags

---

source/cloud/gcp/dataproc.md

Running the copy commands individually seems to succeed more often than running them all in one go.
Also fixes a missing `gs://` later on.
@skirui-source

Fix GCS bucket command

---

source/conf.py

23.02 dropped Python 3.9 so bumping to 3.10.

Fix Python version in 23.02 images

---

extensions/rapids_version_templating.py

Fixed the problem @betatim found in #141 where jinja2 didn't like certain characters. Fixed by using a regex to only apply templating to sections wrapped in `{{ }}`.

Fix template rendering on pages with bad jinja2 characters

---

source/platforms/index.md

Looks like the databricks page wasn't in any TOC anywhere. Adding it to the platforms page.

Add the databricks page to the platforms index

---

extensions/rapids_version_templating.py
source/platforms/kubernetes.md

Fixes #155.
Instead of preprocessing the markdown/notebook files I've switched it up so we are postprocessing the doctree nodes and updating all of the text nodes. This is probably a more robust way to do this anyway. 
The included document fragments will have been fully resolved into nodes by the time we are postprcessing them so the templates will also get applied to them.
**Before**
**After**
I also noticed the one in the Kubernetes page was broken because the linter has added spaces between the curly braces to make it valid YAML. Fixed by wrapping the template in quotes.

Fix version templating

---

source/conf.py

When `copybutton_prompt_text` is set, [sphinx-copybutton will remove the prompt](https://sphinx-copybutton.readthedocs.io/en/latest/use.html#strip-and-configure-input-prompts-for-code-cells) from the beginning of any lines that start with the text you specify. 
I used the regex example from their docs which removes `$`, `>>>` and Ipython things like `In [7]: ` and `Out [7]: `.
Closes #156

Exclude prompts from copybutton

---

source/conf.py

This PR fixes deployment docs build to be compatible with `pydata-sphinx-theme=0.13.0` by adding an empty `icon_links` entry.

[REVIEW] Fix docs build to be `pydata-sphinx-theme=0.13.0` compatible

---

source/_static/css/custom.css
source/_templates/notebooks-tag-filter.html
source/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook.ipynb
source/examples/rapids-ec2-mnmg/notebook.ipynb
source/examples/rapids-sagemaker-higgs/notebook.ipynb
source/examples/rapids-sagemaker-hpo/notebook.ipynb

Closes #188 
Replaced the `dataset` tags with `data-storage` and `data-format` which will be more useful to users.
I also tweaked the template so that hyphenated tags get shown as two words `data-storage` => `Data Storage`.

Change dataset tags to data-storage and data-format

---

.github/workflows/build-and-deploy.yml

Closes #168.
This PR adjusts the `build-and-deploy.yml` workflow to push the documentation files to S3.
This is needed for the upcoming overhaul to the `rapidsai/docs` repository.
I will open a subsequent PR in the future to remove the step from this workflow that commits files directly to that repository.

Upload docs to S3

---

extensions/rapids_version_templating.py

In #181 the version templating is incorrectly matching the Azure ML template string `${{inputs.data_dir}}`.
Added a negative lookbehind to ignore the `${{}}` style templating.

Update regex to exclude invalid templates

---

.github/workflows/build-and-deploy.yml

After adding the `aws-actions/configure-aws-credentials` step in #214, this workflow also needs some updated permissions as described in https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings.
This should fix these errors that have been popping up since that PR was merged:
- https://github.com/rapidsai/deployment/actions/runs/4698469515/jobs/8330783891#step:6:17

Update workflow permissions for AWS credentials

---

.github/workflows/build-and-deploy.yml

This PR removes the step to commit documentation files to `rapidsai/docs`.
We are overhauling that repository. All docs are now uploaded to S3 (see #214).
I didn't expect us to need to remove this step until later in `23.06`, but we're actually moving forward with this overhaul a bit sooner than I expected.

Remove step to commit doc files

---

source/platforms/coiled.md

Coiled does not currently support Ubuntu 22.04 based images which are now our default.
Updating our docs to ensure they still use Ubuntu 20.04 for Coiled and add a warning about Ubuntu 22.04.
xref https://github.com/coiled/feedback/issues/239

Add Coiled Ubuntu 22.04 warning

---

source/platforms/coiled.md

Ubuntu 22.04 images now work on Coiled, reverting rapidsai/deployment#222
cc @ntabris 
Closes #229

Remove Coiled Ubuntu 22.04 warning

---

source/cloud/gcp/gke.md

As a part of #236: Quick fix for cluster name in delete command https://docs.rapids.ai/deployment/nightly/cloud/gcp/gke/

GCP: Fix name in delete command

---

source/_includes/install-rapids-with-docker.md

When testing https://docs.rapids.ai/deployment/nightly/cloud/gcp/compute-engine/ I had to reconnect my SSH because `groups` didn't list me as being a member of the `docker` group, but `/etc/group` did. I suspect this is because I got added to the group after connecting?
I added this note to let people know that all they need to do is reconnect, not go off and `groupadd` people etc. However I am unsure if it makes sense to have this comment everywhere where the docker commands are included? WDYT?

Add note about docker permissions/group

---

source/examples/xgboost-rf-gpu-cpu-benchmark/hpo.py

Update #252 to speed up the CPU RF benchmark. Also, `hpo.py` can now run on a CPU-only instance.

Make the benchmark runnable on CPU-only instance; speed up CPU RF

---

source/cloud/gcp/vertex-ai.md

Closes #265 
This updates the instructions for Vertex AI to match the new UI. The downside of this is that when you start the notebook loading the additional kernel takes "the age of the universe". I stopped waiting after maybe 10min or so.
This means this is kind of a solution, but also not really.
It seems like this method of using your own docker image (or using it in addition) is becoming deprecated. At least that is the feeling I get from how hidden the options are for selecting it.
---
I've tried installing rapids via conda or cudf via pip in a "bog standard" Vertex AI notebook environment. This kinda works. The conda install takes a long time to solve and then fails at the end with a permission error (`[Errno 13] Permission denied: …

Update VertexAI instructions to match new UI

---

source/conf.py

This PR does two things to `conf.py`
1. Updates the Docker pull commands to match the[ RAPIDS 23.08 updates](https://github.com/rapidsai/docker/issues/539)
2. Updates the script so we only need to update the versions in 1 place to reduce human error possibility
It also updates the versions for `23.08` since we'll need to do that prior to release anyway.

Conf.py 23.08 update

---

source/examples/xgboost-rf-gpu-cpu-benchmark/Dockerfile
source/examples/xgboost-rf-gpu-cpu-benchmark/hpo.py

When using VMs with multiple GPUs, it is more advantageous to run multiple training jobs in parallel, rather than running one training job at a time.

Update TCO benchmark to run training jobs in parallel

---

source/cloud/gcp/vertex-ai.md

Closes #290 
The instructions we had previously for installing RAPIDS into Vertex AI Workbench Managed Notebooks no longer work. Something must've changed on their end and importing the RAPIDS environment doesn't work.
This PR updates the instructions to use User-Managed Notebooks instead which give more control over the Python environments.

Fix Vertex AI with user-managed example

---

source/conf.py

Bump the version for the `23.12` release.
Also, switch `cudatoolkit` to `cuda-version` which is the preferred package for selecting the CUDA version since it is compatible with both CUDA 11 & 12.

Updates for 23.12 release

---

source/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook.ipynb

Fixes the `cuspatial.haversine_distance()` example using the public NYC taxi data hosted on GSC ([GSC console link](https://console.cloud.google.com/storage/browser/anaconda-public-data/nyc-taxi/2015.parquet;tab=objects?prefix=&forceOnObjectsSortingFiltering=false)).
Running through the notebook code for that example (the same one that ends up at https://docs.rapids.ai/deployment/nightly/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook/), I encountered 3 issues:
1. needed to authenticate with GCP
```text
ValueError: An error occurred while calling the read_parquet method registered to the cudf backend.
Original Message: An error occurred while calling the read_parquet method registered to the pandas backend.
Original Message: Invalid gcloud credentials
```
2. that GCS bucket …

fix cuspatial.haversine_distance() example in multi-tenant notebook

---

source/_includes/check-gpu-pod-works.md

It looks like the vectoradd containers haven't been updated for a while. We currently mention CUDA 11.2 but there is a more recent (but still not very recent) CUDA 11.6. Bumping it up anyway.

Update validation Pod to latest

---

source/tools/kubernetes/dask-helm-chart.md

The helm chart needs to use the `rapidsai/notebooks` image for the Jupyter service. Also streamlines the install command a little to match other pages where we specify the repo inline.
CLoses #338

Fix helm image and streamline install

---

source/cloud/aws/ec2.md

Just came across this error while connecting to an EC2 instance. The fix was suggested at https://forums.developer.nvidia.com/t/nvidia-gpu-optimized-ami-is-missing-drivers-and-cant-run-the-pytorch-ngc-dockerfile/276492/2 and made a note here in case others come across this.

Update ec2.md with note on failing to install drivers

---

source/cloud/nvidia/index.md

I think it makes sense to link to nvidia.com resources from the DGX Cloud page.

Add link to nvidia.com

---

source/examples/rapids-sagemaker-hpo/notebook.ipynb

Contributes to #333.
Fixes these issues in `rapids-sagemaker-hpo/notebook.ipynb` found by `ruff`:
```text
F403 `from helper_functions import *` used; unable to detect undefined names
F405 `os` may be undefined, or defined from star imports
F405 `recommend_instance_type` may be undefined, or defined from star imports
F405 `summarize_choices` may be undefined, or defined from star imports
F405 `validate_dockerfile` may be undefined, or defined from star imports
E712 Avoid equality comparisons to `True`; use `if use_spot_instances_flag:` for truth checks
F405 `summarize_choices` may be undefined, or defined from star imports
F405 `new_job_name_from_config` may be undefined, or defined from star imports
F405 `summarize_choices` may be undefined, or defined from star imports
F405 …
```

remove use of star imports in rapids-sagemaker-hpo notebook

---

source/examples/rapids-sagemaker-higgs/notebook.ipynb
source/examples/xgboost-azure-mnmg-daskcloudprovider/notebook.ipynb

Contributes to #333
`ruff` reports 2 errors of the form "this Python cell in a notebook doesn't look like syntactically-valid Python code".
```text
error: Failed to parse source/examples/xgboost-azure-mnmg-daskcloudprovider/notebook.ipynb:23:6:27: Unexpected token '<'
error: Failed to parse source/examples/rapids-sagemaker-higgs/notebook.ipynb:39:1:5: Unexpected token 'ecr'
```
This fixes both of those.
Ensuring every Python code is syntactically-valid Python code means we can get better coverage from static analysis and formatting tools, reducing the risk of bugs making it into these notebooks.
I've left comments inline in the diff below explaining how specific changes fix these errors.
All other style changes were made automatically by this project's other formatting hooks. Those …

ensure all notebook Python cells are valid Python code

---

source/examples/rapids-1brc-single-node/notebook.ipynb
source/examples/time-series-forecasting-with-hpo/notebook.ipynb
source/examples/xgboost-dask-databricks/notebook.ipynb
source/examples/xgboost-gpu-hpo-job-parallel-k8s/notebook.ipynb
source/examples/xgboost-gpu-hpo-job-parallel-ngc/notebook.ipynb
source/examples/xgboost-randomforest-gpu-hpo-dask/notebook.ipynb

Contributes to #333
Fixes the following warnings by `ruff`
```text
source/examples/rapids-1brc-single-node/notebook.ipynb:cell 7:1:1: I001 [*] Import block is un-sorted or un-formatted
source/examples/rapids-1brc-single-node/notebook.ipynb:cell 10:8:17: F541 [*] f-string without any placeholders
source/examples/time-series-forecasting-with-hpo/notebook.ipynb:cell 23:18:9: UP032 [*] Use f-string instead of `format` call
source/examples/time-series-forecasting-with-hpo/notebook.ipynb:cell 103:12:26: F541 [*] f-string without any placeholders
source/examples/xgboost-randomforest-gpu-hpo-dask/notebook.ipynb:cell 3:1:1: I001 [*] Import block is un-sorted or un-formatted
source/examples/xgboost-randomforest-gpu-hpo-dask/notebook.ipynb:cell 3:4:8: F401 [*] `cuml` imported but unused …
```

remove unused imports in XGBoost notebooks, fix other small style things

---

source/cloud/aws/ecs.md
source/cloud/aws/sagemaker.md
source/examples/rapids-azureml-hpo/notebook.ipynb

Contributes to #375.
Related to https://github.com/rapidsai/docker/issues/680#issuecomment-2147695884.
There are a few lingering references in deployment docs claiming that RAPIDS supports Pascal GPUs. This proposes:
* updating those
* replacing such references with links out to the RAPIDS docs, to prevent this happening again in the future
Found these like this:
```shell
git grep -i pascal
```

remove references to Pascal

---

source/tools/dask-cuda.md

Contributes to #374 .
Fixes the following in `dask-cuda` docs at https://docs.rapids.ai/deployment/nightly/tools/dask-cuda/:
* marks Python notebook cells as Python code, so that:
- they'll be Python syntax-highlighted when rendered
- linters can cover them in CI
* adds missing imports
- *it isn't obvious from this page that `LocalCUDACluster` is something you import from `dask_cuda`*
* removes `if __name__ == "__main__"` stuff in example
- so that the example code is runnable in a notebook or REPL without the extra friction of writing it to a script

add missing imports for dask-cuda docs

---

source/guides/colocate-workers.md
source/guides/index.md
source/guides/scheduler-gpu-optimization.md

Contributes to #9 
Adds a guide to https://docs.rapids.ai/deployment/stable/guides/
- Creates a cluster on GKE 
- Installs drivers and Dask Operator
- creates a Dask cluster with pod affinity for the worker pods

add guide for worker co-location optimization for multi-GPU usecases

---

.github/workflows/build-and-deploy.yml
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
.readthedocs.yaml
conda/environments/deployment_docs.yml

In preparation for the 24.08 release, proposes updating various versions across the repo.
* updating `pre-commit` hooks via `pre-commit autodupate`
* putting floors on all dependencies in the docs-building conda environment
- *(to make `conda` solves faster, and to prevent weird solves from accidentally rolling us back to, for example, much older versions of `sphinx`)*
* using `os: "ubuntu-lts-latest"` and `python: "mambaforge-latest"` readthedocs configs
- *to avoid the need to make any manual changes here when Ubuntu or `mambaforge` versions go end-of-life*
- *docs: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os*
* updating various third-party GitHub Actions to their latest versions
Makes CI a bit faster.
Improves the likelihood of `pre-commit` hooks catching issues. …

update versions of dependencies

---

source/examples/rapids-sagemaker-higgs/notebook.ipynb

Contributes to #382.
The SageMaker Higgs notebook has a reference to the `rapidsai/rapidsai-core` image's DockerHub page, even though it uses `rapidsai/base`.
https://github.com/rapidsai/deployment/blob/3ee5b951b1b00b8abddc976d2ddd640bc84055e5/source/examples/rapids-sagemaker-higgs/notebook.ipynb#L153
https://github.com/rapidsai/deployment/blob/3ee5b951b1b00b8abddc976d2ddd640bc84055e5/source/conf.py#L30

update DockerHub link in Higgs notebook

---

.pre-commit-config.yaml

Proposes adding `shellcheck` to the pre-commit checks, to look for issues in shell scripts here.
This is done via `shellcheck-py` (https://pypi.org/project/shellcheck-py/), a repackaging of `shellcheck` for PyPI that allows it to be used in pre-commit without needing a separate system installation.
Right now there are just 2 little shell scripts in this repo: https://github.com/search?q=repo%3Arapidsai%2Fdeployment%20path%3A**%2F*.sh&type=code
Both are used as the entrypoints in bring-your-own-container SageMaker examples. So the additional coverage we get from this check, in the current state of the repo, is pretty small.
But it's lightweight to install and runs fast, and could help to catch issues in those scripts or others we add in the future, so on balance I think it's worth adding. …

run shellcheck in pre-commit checks

---

.gitignore
.pre-commit-config.yaml

Just some tiny housekeeping things I noticed while working on #402.
Proposes:
* gitignore-ing extensions that often contain sensitive information, like `.env` and `.pem`
* updating pre-commit hooks to their latest versions, via `pre-commit autoupdate`

gitignore common extensions with sensitive data, update pre-commit hooks

---

source/conf.py

Update the versions for RAPIDS `24.08` release

Update to 24.08

---

source/conf.py

Follow-up to #411.
Contributes to #377.
Context: https://github.com/rapidsai/deployment/pull/411#pullrequestreview-2228703917

use CUDA 12.5 and Python 3.11 in most examples

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
conda/environments/deployment_docs.yml

Since we're nearing another period of heavy activity in this project, testing the 24.10 release, this proposes updating the build and test dependencies here to their latest versions, similar to #396.
* conda env for docs building:
- *Python `3.11 -> 3.12`*
- *all other dependencies with floors on their latest versions (for faster conda solves)*
- *limiting to only `conda-forge`*
* pre-commit hooks to their latest versions
- *via `pre-commit autoupdate`
* GitHub Actions configs:
- *Python `3.11 -> 3.12`*
- *all third-party actions to their latest versions (no changes here, just saying I checked this)*

update build and test dependencies

---

source/platforms/colab.md

We are updating where our Colab notebooks live, including this one   This is the corrected link.

update colab link

---

.github/workflows/build-and-deploy.yml

The most recent build job on `main` failed like this:
> Warning: Future Miniforge releases will NOT build Mambaforge installers. We advise you switch to Miniforge at your earliest convenience. More details at [https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/.](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/)
Warning: ERROR: executing pre_install.sh failed
ERROR: executing pre_install.sh failed
([build link](https://github.com/rapidsai/deployment/actions/runs/11123300853/job/30906464297))
This comes from the `conda-incubator/setup-miniconda` action. Luckily, I just experienced the same thing on a little side-project I work on (https://github.com/jameslamb/pydistcheck/pull/263)... the fix is to switch from mambaforge to miniforge.
This does that, to get builds …

switch to miniforge in build-and-deploy job

---

.pre-commit-config.yaml

#74 introduced an empty `.markdownlintignore` file, and that file appears to have been empty ever since.
I think it's safe to remove, and that doing so would slightly simplify this repo.
This proposes that removal.
Let's not merge until @jacobtomlinson specifically reviews... there might be some context I'm missing that explains why this empty file was added back in #74.

simplify markdownlint configuration

---

source/cloud/aws/ec2.md

Contributes to #434
The button for launching an EC2 instance using the official "NVIDIA GPU-Optimized AMI" now has language about 
"subscribing" instead of just saying "Select".
Other than this, https://docs.rapids.ai/deployment/nightly/cloud/aws/ec2 is good, so I checked it off on #434

update EC2 instructions (button text changed)

---

source/cloud/aws/sagemaker.md
source/cloud/azure/azureml.md

Two examples have this commented-out code in setup scripts for creating development environments:
```text
```
This proposes removing those... they seem unnecessary. I suspect they were just carried over from something else and forgotten about (e.g. the SageMaker ones came over 1.5+ years ago in #126).
There aren't any AutoML or gluon examples in this project.
```shell
git grep -i gluon
git ls-files | grep -i gluon
git grep -i automl
git ls-files | grep -i automl
```

remove commented-out 'autogluon' installs

---

source/cloud/gcp/vertex-ai.md

I initially had trouble finding the `workbench` tab because the `NOTEBOOKS` tab was closed by default, so I was browsing through the `VERTEX AI STUDIO` tab the whole time. 
Pointing users towards the destination `workbench` tab would be easier by providing an intermediary step (the `NOTEBOOKS` tab)

added notebook instruction

---

source/tools/dask-cuda.md

Fixes #449
I'd thought that the templating introduced in #403 was broken, but just looks like one URL was missing the template markers. I've fixed that here.
Checked for other such mistakes like this:
```shell
git grep 'rapids_api_docs_ver'
```
Didn't find any.

fix version in dask-cuda link

---

source/cloud/gcp/gke.md

Currently the entirety of the multiline command isn't copied over when users hit the `copy` code block button (only the first line)
Turning the multiline block into a single line 
More convenient for users to copy and paste 
May be harder to read and interpret each of the configurations in the arguments

fixed copy code block bug

---

source/platforms/colab.md

I ran through the colab demo today (https://docs.rapids.ai/deployment/nightly/platforms/colab), with the 24.10 nightlies.
Even found a bug in the installer! (https://github.com/rapidsai-community/rapidsai-csp-utils/pull/112)
This proposes the following changes based on that experience:
* remove links that are overly-general or that point to archived repos
* be consistent about use of "RAPIDS" vs. "RAPIDSAI"
* point to the install selector instead of enumerating GPU types

Google Colab: clarify language, remove outdated links

---

pyproject.toml
source/cloud/aws/sagemaker.md
source/examples/rapids-sagemaker-higgs/notebook.ipynb

Proposes the following updates to https://docs.rapids.ai/deployment/nightly/cloud/aws/sagemaker/
* guard downloads of the `HIGGS.csv` file with `if` statements so you don't have to wait to re-download the data if it already exists locally
- *helpful, because downloading the data can take 10+ minutes*
* ~put a floor of `sagemaker>=2.198` in the lifecycle configuration script used to create the `rapids` JupyterLab kernel for the SageMaker notebook instance~
I'd originally also added a floor on the `sagemaker` Python here, but reverted that per https://github.com/rapidsai/deployment/pull/446#discussion_r1790589446.
<details><summary>details about why I'd added that sagemaker floor at first (click me)</summary>
Without that floor on `sagemaker`, even just running `import sagemaker` at the top …

SageMaker example: make downloads conditional

---

source/platforms/coiled.md

Add a couple of small tweaks to the Coiled instructions.

Fix code typo for Coiled

---

source/cloud/aws/eks.md

It seems that a lot of the issues we were having were related to using the NVIDIA GPU Operator on EKS with Amazon Linux nodes. To simplify things I've updated the docs to just use the default driver install that EKS does for you. This gives you much less control than the GPU Operator, but should be more than suitable for beginners.
This allows us to simplify the docs here and get things working OOTB again.
Closes #409 
Closes #459

Fix EKS instructions for 24.10 testing

---

conda/environments/deployment_docs.yml

Looks like sphinx 8.1.0 broke `sphinxcontrib-mermaid` which in turn broke builds here. Adding an upper bound pin to sphinx until this is resolved.
I've also opened https://github.com/mgaitan/sphinxcontrib-mermaid/pull/161 to contribute a fix upstream which will allow us to remove the upper bound again.
Closes #463

Add upper bound pin temporarily to sphinx to avoid breakages

---

source/cloud/azure/azure-vm.md
source/examples/rapids-azureml-hpo/notebook.ipynb
source/examples/rapids-optuna-hpo/notebook.ipynb
source/platforms/kubeflow.md
source/tools/kubernetes/dask-operator.md

I was going over the docs and found multiple broken links and some typos, so I went ahead and fix them. In some situations I wasn't sure about the correct link, please double check they are pointing to were they are supposed to.

Fix broken links and some typos

---

source/examples/rapids-sagemaker-hpo/notebook.ipynb

Closes #468 
Let's give it a try and see what happens in the rendering when using markdown-style hyperlinks.  
Edit: I check the read the doc link and looks like it works 🚀

fix image rendering in rapid-sagemaker-hpo notebook

---

source/platforms/coiled.md

Based on discussion in https://github.com/rapidsai/deployment/pull/456#discussion_r1796927267, sounds like this example shouldn't include `cluster` as an argument to `Client` as this should be implicitly picked up from within a Jupyter server spun up as part of a Coiled cluster.

Amend Coiled cluster example on Jupyter

---

source/examples/rapids-1brc-single-node/notebook.ipynb

Fixes a broken link in the 1 Billion Row Challenge notebook.

fix link to RAPIDS install docs

---

source/guides/mig.md

Closes https://github.com/rapidsai/deployment/issues/151
These are the places where we import, link or mention pynvml https://github.com/search?q=repo%3Arapidsai%2Fdeployment+pynvml&type=code 
As part of this PR I manually went over these with a RAPIDS 25.02 nightly installation and check they worked as expected.
Questions remaining: 
-  Here we are installing `pynvml` but we also install `rapids` which comes with `pynvml` do we want to remove then specific package or replace it for `nvidia-ml-py` https://github.com/rapidsai/deployment/blob/370c7222c0882f3fecc57f3bcc267f7cfba249ea/source/guides/azure/infiniband.md?plain=1#L261 
- Do we want to try this in azure itself, or the confirmation of running a similar installation locally and running this is sufficient? …

Check pynvml works after move to nvidia-ml-py

---

source/cloud/aws/ec2.md

updated the EC2 docs to reflect UI changes and possible challenges the user may face in deploying RAPIDS on an EC2 cluster as they work through the process

add some clarification for the ec2 deployment process

---

README.md
source/conf.py

Update stable to 25.02 and nightly to 25.04; updates cuda versions as well in README as well.

Bump rapids, cuda versions

---

source/cloud/aws/eks.md

Update EKS deployment docs clarifying ssh key steps, and including some notes that help during the deployment process.

Improve eks deployment docs

---

source/cloud/azure/azureml.md

Looks like the conda command is failing because the lines aren't escaped correctly. This should fix things.

Add missing slash to AzureML startup script

---

source/cloud/azure/aks.md

AKS no longer supports selecting their OS image with GPU drivers. Instead you need to use the GPU operator to install drivers.

Use GPU operator on AKS nodes

---

scripts/gen_release_checklist_issue.py

The last couple of releases I had to manually remove some `.ipynb_checkpoints` entries from the generated list. This PR updates the script so that they don't get included in the first place.

Ignore .ipynb_checkpoints in release checklist script

---

ci/release/update-version.sh

This PR adds support for the RAPIDS release process to the deployment repository.
Changes:
- Add `ci/release/update-version.sh` script to handle version updates
- Script updates:
- Stable and nightly versions in `source/conf.py`
- Container references in both `conf.py` and `README.md`
Manual steps:
- I created a `branch-25.04` branch to establish version reference for the burndown script.
And:
- No changes needed to the existing `build-and-deploy.yml` workflow
This ensures that the deployment repository can be properly versioned and released as part of the regular RAPIDS release cycle.

Add support for RAPIDS release process

---

source/conf.py

Looks like the upstream CSS got broken and we need to explicitly include font awesome now.
**Before**
**After**

Add missing Font Awesome css

---

extensions/rapids_admonitions.py
source/_static/css/custom.css

Closes #522 
Updates the custom admonition styling to follow the colour customisation conventions mentioned in the [PyData Sphinx Theme docs](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/extending.html#customizing-the-color).
**Before**
**After** ([Live Preview](https://rapids-deployment--559.org.readthedocs.build/en/559/examples/xgboost-rf-gpu-cpu-benchmark/notebook/))

Fix styling issues in docref admonition

---

scripts/unused_images.sh

On my machine the `unused-images` pre-commit hook was taking ~35s. It seemed to be because it was traversing folders at the root level of the repo like `node_modules`. There were excludes for these but it wasn't working in the way I expected.
This PR updates the script to explicitly only check for images stored within `source/` and ensures they are referenced either in `source/` or the main `README.md`. This change reduces execution time to around 1 second.

Speed up unused images pre-commit hook

---

source/conf.py

Towards #584 (we will need to bump stable as part of the release cc @AyodeAwe)

Bump nightly tags to CUDA 12.9

---

source/guides/colocate-workers.md
source/guides/scheduler-gpu-optimization.md
source/platforms/kubeflow.md
source/platforms/kubernetes.md
source/tools/index.md
source/tools/kubernetes/dask-operator.md
source/tools/rapids-docker.md

Towards https://github.com/rapidsai/deployment/issues/582
Now that we have a separate page describing in detail about running RAPIDS in Docker containers, this page with just a redirect can be safely removed. 
Also changed all the references of RAPIDS docker containers to the official [RAPIDS Docker Install page](https://docs.rapids.ai/install/#docker)

remove redundant Docker images page

---

source/guides/azure/infiniband.md

UCX-Py is being archived, therefore instructions need to be updated to refer/use UCXX.

Update instructions to UCXX
